language: php

services:
  - mongodb

matrix:
  fast_finish: true
  include:
    - php: 7.1
      env: DRIVER_VERSION=stable SERVER_VERSION=3.4
      addons:
        apt:
          sources:
            - sourceline: "deb [arch=amd64] https://repo.mongodb.org/apt/ubuntu precise/mongodb-org/3.4 multiverse"
              key_url: "https://www.mongodb.org/static/pgp/server-3.4.asc"
            - "mongodb-upstart"
          packages: ['mongodb-org-server']

before_install:
  - pecl install -f mongodb-${DRIVER_VERSION}

before_script:
  - mongo imagehub-test --eval 'db.createUser({user:"imagehubuser",pwd:"imagehubpass",roles:[ "readWrite", "dbAdmin" ]});'
  - composer install
  - app/console app:setup --env=test
  
script:
  - bin/phpunit

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
