imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en
    app.locales: en|nl

framework:
    #esi: ~
    #translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
        locales: '%app.locales%'
        service_name: '%service_name%'
        service_address: '%service_address%'
        service_organisation: '%service_organisation%'
        service_organisation_website: '%service_organisation_website%'

# Doctrine Configuration
doctrine_mongodb:
    default_database: %mongodb_database%
    connections:
        default:
            server: %mongodb_server%
            options:
                username: %mongodb_user%
                password: %mongodb_password%
                db: admin
    document_managers:
        default:
            auto_mapping: true

# Swiftmailer Configuration
#swiftmailer:
#    transport: '%mailer_transport%'
#    host: '%mailer_host%'
#    username: '%mailer_user%'
#    password: '%mailer_password%'
#    spool: { type: memory }

sensio_framework_extra:
   router:
        annotations: false
