parameters:
    images_folder: '../images/'
    supported_extensions:
        - tif

    exif_fields:
        # dataPid is required to fetch the relevant record from the Datahub
        data_pid:
            exif: 'ImageDescription'
            field: 'pidafbeelding'
        # originalfilename is required to find the matching resource in ResourceSpace
        originalfilename:
            exif: 'FileName'
            field: 'originalfilename'
        # All other fields are optional
        camera:
            exif: 'Model'
            field: 'camera'
        mime_type:
            exif: 'MimeType'
            field: 'digitalsourcetype'
        file_size:
            exif: 'FileSize'
            field: 'videosize'
        work_pid:
            exif: 'DocumentName'
            field: 'pidobject'
        right_usage_terms:
            exif: 'Copyright'
            field: 'rightusageterms'
        creator_of_image:
            exif: 'Artist'
            field: 'creatorofimage'
        credit_line:
            exif: 'Artist'
            field: 'creditline'
        date_created:
            exif: 'DateTimeOriginal'
            field: 'datecreatedofimage'

    api_url: 'http://resourcespace.box/api'
    api_username: 'admin'
    api_key: 'a63be2826ee346f6ef7bafc06d9aef642e007a213214fd8624eebbd0818adac2'

    datahub.url: 'http://datahub.box/oai'
    datahub.language: 'nl'
    datahub.namespace: 'lido'
    datahub.metadataprefix: 'oai_lido'
    datahub.data_definition:
        publisher:
            xpath: 'administrativeMetadata[@xml:lang="{language}"]/recordWrap/recordSource/legalBodyName/appellationValue'
            field: 'publisher'
        title:
            xpath: 'descriptiveMetadata[@xml:lang="{language}"]/objectIdentificationWrap/titleWrap/titleSet/appellationValue'
            field: 'titleofartworkobject'
        short_description:
            xpath: 'descriptiveMetadata[@xml:lang="{language}"]/objectIdentificationWrap/objectDescriptionWrap/objectDescriptionSet/descriptiveNoteValue'
            field: 'description'
        creator:
            xpath: 'descriptiveMetadata[@xml:lang="{language}"]/eventWrap/eventSet/event[eventType/term="production"]/eventActor/actorInRole/actor/nameActorSet/appellationValue[@pref="preferred"]'
            field: 'creatorofartworkobje'
        period:
            xpath: 'descriptiveMetadata[@xml:lang="{language}"]/eventWrap/eventSet/event[eventType/term="production"]/periodName/term'
            field: 'work-period'
        keywords:
            xpaths:
              - 'descriptiveMetadata[@xml:lang="{language}"]/objectClassificationWrap/objectWorkTypeWrap/objectWorkType/conceptID[@source="AAT"]'
              - 'descriptiveMetadata[@xml:lang="{language}"]/objectClassificationWrap/objectWorkTypeWrap/objectWorkType/term[@pref="preferred"]'
            field: 'keywords'

services:
    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    AppBundle\ResourceSpace\:
        resource: '../../src/AppBundle/ResourceSpace/*'
        # you can exclude directories or files
        # but if a service is unused, it's removed anyway
        exclude: '../../src/AppBundle/ResourceSpace/{Entity,Repository,Tests}'

    app.command.fill_resourcespace_command:
        class: AppBundle\ResourceSpace\Command\FillResourceSpaceCommand
        tags:
            -  { name: console.command }
