parameters:
    images_folder: '../images/'
    supported_extensions:
        - tif

    exif_fields:
        workPid:
            exif: 'DocumentName'
            field: 'work-workpid'
        # dataPid is required, to fetch the relevant record from the Datahub
        dataPid:
            exif: 'ImageDescription'
            field: 'work-datapid'

    api_url: 'http://resourcespace.box/api'
    api_username: 'admin'
    api_key: 'b1603c459927151cfec1d8f691170975d13ecc5bf4bcaa4fad1f5cf2b7e2e46c'

    datahub.url: 'http://datahub.box/oai'
    datahub.namespace: 'lido'
    datahub.metadataprefix: 'oai_lido'
    datahub.data_definition:
        title:
            xpath: 'descriptiveMetadata[@xml:lang="{language}"]/objectIdentificationWrap/titleWrap/titleSet/appellationValue'
            field: 'title'
        short_description:
            xpath: 'descriptiveMetadata[@xml:lang="{language}"]/objectIdentificationWrap/objectDescriptionWrap/objectDescriptionSet/descriptiveNoteValue'
            field: 'work-description'
        creator:
            xpath: 'descriptiveMetadata[@xml:lang="{language}"]/eventWrap/eventSet/event[eventType/term="production"]/eventActor/actorInRole/actor/nameActorSet/appellationValue[@pref="preferred"]'
            field: 'work-creator'
        period:
            xpath: 'descriptiveMetadata[@xml:lang="{language}"]/eventWrap/eventSet/event[eventType/term="production"]/periodName/term'
            field: 'work-period'

services:
    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\ResourceSpace\:
        resource: '../src/ResourceSpace/*'
        exclude: '../src/ResourceSpace/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    app.command.fill_resourcespace_command:
        class: App\ResourceSpace\Command\FillResourceSpaceCommand
        tags:
            -  { name: console.command }
